### ISSUE TITLE
saxon-lint cannot work with files in the current directory

### ISSUE THREAD

**Issue by wabiloo** [sputnick-dev/saxon-lint#1]
It seems that the only way to work with XML files is by providing full path to the XML file, or having the XML file in the same directory as saxon-lint.pl

➜  ls ./iPlayer-20131212.xml  
./iPlayer-20131212.xml

➜  saxon-lint.pl --xpath 'distinct-values(/Content/*/name())' iPlayer-20131212.xml
Source file iPlayer-20131212.xml does not exist

**Comment by sputnick-dev** [comment]
Thanks to report, fixed in the new commits.
