### ISSUE TITLE
XSLT output not working

### ISSUE THREAD

**Issue by terijaki** [sputnick-dev/saxon-lint#7]
## Problem
I have tried a few way to have the XSLT processor output to a file I specify via command but I can't get `-o` to output the result to a specified file.

## Context
I would like to use saxon over xsltproc to benefit from XSLT V2.0. What I am trying to replace is an existing process that is using `xsltproc mytemplate.xslt mysource.xml.xml > mytarget.html`
I do not have any file output specified in .xslt file because I need to handle this dynamically by calling the XSLT processor.

## Steps to reproduce
This works fine 👍
`saxon-lint.pl --xslt "mytemplate.xslt" "mysource.xml"` 

This should output the results into a file but **instead prints it to the console** 😕
`saxon-lint.pl --xslt "mytemplate.xslt" "mysource.xml" -o "target.html"` 

Using `-xsl `or `-s` to specify template and source don't seem to have any affect.

**Comment by sputnick-dev** [comment]
There's no `-o` switch.

Please, use :

    saxon-lint.pl --xslt "mytemplate.xslt" "mysource.xml" | tee "target.html"

or

    saxon-lint.pl --xslt "mytemplate.xslt" "mysource.xml"  > "target.html"

**Comment by terijaki** [comment]
Oh boi.. thank you! 🤗
